"""NDL IIIF client: manifest fetch, page registration, polite image retrieval.

Layer 1. Registers a roster volume and its pages from the NDL IIIF manifest, and
fetches page images into the private data home. Stdlib only.

Like scripts/load_vocab.py, registration emits SQL on stdout rather than
speaking to the database directly — no driver dependency, works against any
psql, and the audit triggers record the writes like any others:

    python ingestion/iiif_client.py register 1449474 | docker exec -i jpocr-db \
        psql -U jpocr -d jpocr -v ON_ERROR_STOP=1 -f -

Image fetch caches under %JP_OCR_DATA%/cache/{pid}/ and never overwrites:

    python ingestion/iiif_client.py fetch 1449474 51

Politeness: one request at a time, a fixed delay between image requests
(Spike B observed ~1.5 s/image as the working rate), an identifying UA, and
resumable caching so re-runs cost NDL nothing.
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.request
from pathlib import Path

MANIFEST_URL = "https://dl.ndl.go.jp/api/iiif/{pid}/manifest.json"
USER_AGENT = "jp-vertical-ocr-optimization (research ingestion; polite, cached)"
IMAGE_DELAY_S = 1.5


def _get(url: str, *, timeout: int = 60) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read()


def manifest(pid: str) -> dict:
    return json.loads(_get(MANIFEST_URL.format(pid=pid)).decode("utf-8"))


def canvases(man: dict) -> list[dict]:
    """Flatten a IIIF v2 manifest to [{frame_no, image_url, width, height}].

    Frame numbers are 1-based positions in the sequence — the same numbering the
    NDL viewer shows and the worklist uses.
    """
    out = []
    for seq in man.get("sequences", []):
        for i, canvas in enumerate(seq.get("canvases", []), start=1):
            images = canvas.get("images", [])
            resource = images[0].get("resource", {}) if images else {}
            service = resource.get("service", {})
            out.append({
                "frame_no": i,
                "image_url": resource.get("@id"),
                "service_id": service.get("@id"),
                "width": canvas.get("width"),
                "height": canvas.get("height"),
            })
    return out


def _q(value) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def register_sql(pid: str, man: dict) -> str:
    """SQL that registers the volume and its pages, idempotently.

    The volume is matched by pid; pages rely on UNIQUE (volume_id, frame_no).
    Re-running after a partial ingest only adds what is missing, and every row
    the script does write is picked up by the audit triggers.
    """
    label = man.get("label", "")
    if isinstance(label, dict):  # IIIF v3-style language map, just in case
        label = next(iter(label.values()), [""])[0]
    cvs = canvases(man)
    lines = [
        "-- Generated by ingestion/iiif_client.py. Do not edit by hand.",
        "SET client_encoding = 'UTF8';",
        "BEGIN;",
        "DO $$",
        "DECLARE v_vol uuid;",
        "BEGIN",
        f"    SELECT volume_id INTO v_vol FROM source_volume WHERE pid = {_q(pid)};",
        "    IF v_vol IS NULL THEN",
        "        INSERT INTO source_volume",
        "            (title, series, pid, holding_institution, iiif_manifest_url, source_url, retrieved_at)",
        "        VALUES",
        f"            ({_q(label)}, '停年名簿', {_q(pid)}, 'NDL',",
        f"             {_q(MANIFEST_URL.format(pid=pid))},",
        f"             {_q('https://dl.ndl.go.jp/pid/' + pid)}, now())",
        "        RETURNING volume_id INTO v_vol;",
        "    END IF;",
    ]
    for c in cvs:
        lines.append(
            "    INSERT INTO source_page (volume_id, frame_no) "
            f"VALUES (v_vol, {c['frame_no']}) "
            "ON CONFLICT (volume_id, frame_no) DO NOTHING;"
        )
    lines += [
        "END $$;",
        "COMMIT;",
        f"-- {len(cvs)} canvases in manifest",
    ]
    return "\n".join(lines) + "\n"


def data_home() -> Path:
    home = os.environ.get("JP_OCR_DATA")
    if not home:
        raise SystemExit("JP_OCR_DATA is not set (see docs/data-home.md)")
    return Path(home)


def fetch_page(pid: str, frame_no: int, *, out_dir: Path | None = None) -> Path:
    """Fetch one page image at full resolution into the cache; skip if cached."""
    out_dir = out_dir or (data_home() / "cache" / pid)
    out_dir.mkdir(parents=True, exist_ok=True)
    dest = out_dir / f"frame_{frame_no:04d}.jpg"
    if dest.exists() and dest.stat().st_size > 0:
        print(f"cached: {dest}", file=sys.stderr)
        return dest

    man = manifest(pid)
    cvs = {c["frame_no"]: c for c in canvases(man)}
    if frame_no not in cvs:
        raise SystemExit(f"frame {frame_no} not in manifest ({len(cvs)} canvases)")
    c = cvs[frame_no]
    url = c["image_url"] or (c["service_id"] + "/full/full/0/default.jpg")

    time.sleep(IMAGE_DELAY_S)
    data = _get(url, timeout=120)
    tmp = dest.with_suffix(".part")
    tmp.write_bytes(data)
    tmp.replace(dest)
    print(f"fetched: {dest} ({len(data)} bytes)", file=sys.stderr)
    return dest


def main(argv: list[str]) -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", newline="\n")
    if len(argv) >= 2 and argv[0] == "register":
        sys.stdout.write(register_sql(argv[1], manifest(argv[1])))
    elif len(argv) >= 3 and argv[0] == "fetch":
        fetch_page(argv[1], int(argv[2]))
    else:
        raise SystemExit(__doc__)


if __name__ == "__main__":
    main(sys.argv[1:])
