-- ===========================================================================
-- jp-vertical-ocr-optimization -- relational core (SQLite)
--
-- Ported from Postgres 2 Aug 2026 by the lead's decision (PLAN.md decision 9).
-- The database is the deliverable, and it has to be shareable, openable and
-- readable by other researchers. That means one file you can copy, not a server
-- someone has to run: SQLite is opened by DB Browser, pandas, R and Excel with
-- no credentials and nothing installed.
--
-- The table design is unchanged from the frozen Postgres schema. What changed is
-- only what Postgres offered and SQLite does not:
--
--   uuid            -> TEXT (still uuid4 strings, generated by app/db.py). Ids
--                      stay uuids precisely because copies get merged: two people
--                      transcribing on two machines must not collide.
--   jsonb / text[]  -> TEXT holding JSON. SQLite's json1 functions read it.
--   timestamptz     -> TEXT, ISO-8601 UTC.
--   audit triggers  -> work_log, written by the application (see below).
--
-- Invariants this schema is built to enforce, unchanged:
--   * observation.person_id stays NULL until linked, so unlinked records are
--     never silently dropped.
--   * No machine-authored final values: machine_reading is a separate table and
--     can never be the source of an observation field.
--   * reference_truth is walled off from production data and carries its own
--     train/hold-out flag.
--   * unit and unit_deployment are temporal, so officer-year theater assignment
--     is derivable.
--
-- Foreign keys are OFF by default in SQLite. app/db.py turns them on for every
-- connection; anything else touching this file must do the same.
-- ===========================================================================

PRAGMA foreign_keys = ON;

-- --------------------------------------------------------------------------
-- Controlled vocabularies
-- --------------------------------------------------------------------------

CREATE TABLE rank_vocab (
    rank_code       TEXT PRIMARY KEY NOT NULL,  -- e.g. 'shoi', 'chui', 'taii'
    label_ja        TEXT NOT NULL,              -- 少尉 / 中尉 / 大尉
    label_en        TEXT,
    seniority_order INTEGER NOT NULL,           -- ascending; enables rank-consistency checks
    variants        TEXT NOT NULL DEFAULT '[]', -- JSON array of kyujitai / orthographic variants
    valid_from      TEXT,
    valid_to        TEXT
);

CREATE TABLE branch_vocab (
    branch_code TEXT PRIMARY KEY NOT NULL,      -- e.g. 'hohei', 'kihei', 'hohei_ho'
    label_ja    TEXT NOT NULL,                  -- 歩兵 / 騎兵 / 砲兵
    label_en    TEXT,
    category    TEXT CHECK (category IN ('combat','service')),  -- 兵科 vs 各部
    variants    TEXT NOT NULL DEFAULT '[]',
    valid_from  TEXT,
    valid_to    TEXT
);

-- Kanji variant equivalence, so 齋/斎 is never scored as a disagreement.
CREATE TABLE kanji_variant (
    variant_char   TEXT PRIMARY KEY NOT NULL,
    canonical_char TEXT NOT NULL,
    note           TEXT
);

-- --------------------------------------------------------------------------
-- Provenance: volumes, pages, cells
-- --------------------------------------------------------------------------

CREATE TABLE source_volume (
    volume_id           TEXT PRIMARY KEY NOT NULL,
    title               TEXT NOT NULL,
    series              TEXT,                   -- 停年名簿 / 列次名簿 / Kanpo / manual
    edition_date        TEXT,
    pid                 TEXT,                   -- NDL persistent identifier
    holding_institution TEXT,
    iiif_manifest_url   TEXT,
    source_url          TEXT,
    retrieved_at        TEXT,
    coverage_notes      TEXT
);

CREATE TABLE layout_template (
    template_id  TEXT PRIMARY KEY NOT NULL,
    name         TEXT NOT NULL,                 -- e.g. 'showa-teinen-meibo-A'
    series       TEXT,
    era          TEXT,                          -- meiji / taisho / showa
    -- Column grid defined ONCE per layout family. Field identity comes from
    -- geometry, never from guessing cell contents.
    column_spec  TEXT NOT NULL,                 -- JSON [{field, x0, x1, ...}, ...]
    row_spec     TEXT,
    notes        TEXT,
    created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE source_page (
    page_id     TEXT PRIMARY KEY NOT NULL,
    volume_id   TEXT NOT NULL REFERENCES source_volume(volume_id),
    frame_no    INTEGER NOT NULL,
    template_id TEXT REFERENCES layout_template(template_id),
    alt_scans   TEXT NOT NULL DEFAULT '[]',     -- other institutional scans of same page
    UNIQUE (volume_id, frame_no)
);

CREATE TABLE roster_cell (
    cell_id      TEXT PRIMARY KEY NOT NULL,
    page_id      TEXT NOT NULL REFERENCES source_page(page_id),
    row_index    INTEGER NOT NULL,              -- position on page
    seniority_no INTEGER,                       -- the monotone row anchor
    crop_bbox    TEXT NOT NULL,                 -- JSON [x, y, w, h]
    crop_url     TEXT,                          -- IIIF region URL -- re-checkable
    audit_status TEXT NOT NULL DEFAULT 'ok'
        CHECK (audit_status IN ('ok','sequence_break','extra_row','missing_row','damaged')),
    UNIQUE (page_id, row_index)
);

-- --------------------------------------------------------------------------
-- Units (temporal) and deployments
-- --------------------------------------------------------------------------

CREATE TABLE unit (
    unit_id        TEXT PRIMARY KEY NOT NULL,
    canonical_name TEXT NOT NULL,
    echelon        TEXT,                        -- division / brigade / regiment / battalion
    parent_unit_id TEXT REFERENCES unit(unit_id),
    home_garrison  TEXT,                        -- 衛戍地
    valid_from     TEXT,
    valid_to       TEXT
);

CREATE TABLE unit_deployment (
    deploy_id      TEXT PRIMARY KEY NOT NULL,
    unit_id        TEXT NOT NULL REFERENCES unit(unit_id),
    interval_start TEXT NOT NULL,
    interval_end   TEXT,
    location       TEXT,
    theater        TEXT NOT NULL
        CHECK (theater IN ('home','korea','manchuria','china','taiwan','other')),
    source_refs    TEXT NOT NULL DEFAULT '[]',  -- JSON; citations are mandatory in practice
    confidence     TEXT NOT NULL DEFAULT 'medium'
        CHECK (confidence IN ('high','medium','low')),
    CHECK (interval_end IS NULL OR interval_end >= interval_start)
);

-- --------------------------------------------------------------------------
-- People and observations
-- --------------------------------------------------------------------------

CREATE TABLE person (
    person_id          TEXT PRIMARY KEY NOT NULL,
    canonical_name     TEXT NOT NULL,
    name_readings      TEXT NOT NULL DEFAULT '[]',  -- JSON; furigana
    aliases            TEXT NOT NULL DEFAULT '[]',  -- JSON; mid-career name changes
    birthplace         TEXT,
    social_class       TEXT,
    cohort_no          INTEGER,
    commissioning_date TEXT,
    academy_dataset_id TEXT                     -- link to the existing academy dataset
);

CREATE TABLE observation (
    obs_id             TEXT PRIMARY KEY NOT NULL,
    -- NULL until linked. Unlinked observations are kept, never dropped.
    person_id          TEXT REFERENCES person(person_id),
    page_id            TEXT NOT NULL REFERENCES source_page(page_id),
    cell_id            TEXT NOT NULL REFERENCES roster_cell(cell_id),
    name_raw           TEXT,
    rank_code          TEXT REFERENCES rank_vocab(rank_code),
    branch_code        TEXT REFERENCES branch_vocab(branch_code),
    post               TEXT,                    -- 職名
    unit_id            TEXT REFERENCES unit(unit_id),
    seniority_no       INTEGER,
    commissioning_date TEXT,                    -- 任官年月日
    as_of_date         TEXT NOT NULL,           -- the volume's snapshot date
    field_confidence   TEXT NOT NULL DEFAULT '{}',  -- JSON
    -- Provenance of the human decision. A machine may never populate this.
    author_user_id     TEXT REFERENCES app_user(user_id),
    status             TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft','confirmed','flagged','adjudicated')),
    propagated_from    TEXT REFERENCES observation(obs_id),
    created_at         TEXT NOT NULL DEFAULT (datetime('now'))
);

-- --------------------------------------------------------------------------
-- Kanpo events
-- --------------------------------------------------------------------------

CREATE TABLE kanpo_event (
    event_id              TEXT PRIMARY KEY NOT NULL,
    person_id             TEXT REFERENCES person(person_id),
    event_type            TEXT NOT NULL
        CHECK (event_type IN ('commission','promote','assign','reserve','death')),
    name_raw              TEXT NOT NULL,
    old_rank_code         TEXT REFERENCES rank_vocab(rank_code),
    new_rank_code         TEXT REFERENCES rank_vocab(rank_code),
    branch_code           TEXT REFERENCES branch_vocab(branch_code),
    unit_ref              TEXT,
    event_date            TEXT NOT NULL,
    gazette_ref           TEXT NOT NULL,        -- issue / page / section
    extraction_confidence REAL,
    -- Every event is a PROPOSAL until validated against roster continuity.
    validation_status     TEXT NOT NULL DEFAULT 'proposed'
        CHECK (validation_status IN ('proposed','validated','rank_inconsistent','rejected'))
);

-- --------------------------------------------------------------------------
-- Machine readings -- second opinions only, never authoritative
-- --------------------------------------------------------------------------

CREATE TABLE machine_reading (
    reading_id   TEXT PRIMARY KEY NOT NULL,
    cell_id      TEXT NOT NULL REFERENCES roster_cell(cell_id),
    -- Three proposal sources per reading/README.md, named per the NDL family
    -- convention in docs/ndl-prior-work.md. 'ndl_fulltext' is kept distinct from
    -- the engines we run ourselves: it is NDL's precomputed FY2021 NDLOCR text,
    -- retrieved rather than produced, and is the zero-cost first engine.
    engine       TEXT NOT NULL CHECK (engine IN (
                     'ndl_fulltext',    -- NDL precomputed text via fulltext-json
                     'ndlocr_lite',     -- NDLOCR-Lite, modern typeset, run by us
                     'ndlkoten_lite',   -- NDLkotenOCR-Lite, classical, run by us
                     'vlm'              -- VLM / OCR-free extractor
                 )),
    field        TEXT NOT NULL,
    value        TEXT,
    confidence   REAL,
    agree_status TEXT CHECK (agree_status IN ('agree','disagree','variant_equal','no_human_value')),
    created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- --------------------------------------------------------------------------
-- Ground truth -- walled off, split fixed before first use
-- --------------------------------------------------------------------------

CREATE TABLE reference_truth (
    truth_id         TEXT PRIMARY KEY NOT NULL,
    scope            TEXT NOT NULL,             -- 'year:1925' / 'page:<pid>:<frame>'
    verified_records TEXT NOT NULL,             -- JSON
    provenance       TEXT NOT NULL,
    use_flag         TEXT NOT NULL CHECK (use_flag IN ('train','holdout')),
    registered_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- --------------------------------------------------------------------------
-- Linkage, people, work log
-- --------------------------------------------------------------------------

CREATE TABLE linkage_decision (
    decision_id TEXT PRIMARY KEY NOT NULL,
    obs_id      TEXT REFERENCES observation(obs_id),
    event_id    TEXT REFERENCES kanpo_event(event_id),
    person_id   TEXT NOT NULL REFERENCES person(person_id),
    score       REAL,
    method      TEXT NOT NULL CHECK (method IN ('propagation','splink_auto','adjudicated')),
    decider     TEXT REFERENCES app_user(user_id),
    rationale   TEXT,
    decided_at  TEXT NOT NULL DEFAULT (datetime('now')),
    -- Exactly one of the two: a decision links either an observation or an event.
    CHECK (((obs_id IS NOT NULL) + (event_id IS NOT NULL)) = 1)
);

-- A worker is identified by the id code they were issued, which is `login`
-- (PLAN.md decision 7). No password column and no role: the requirement is that
-- work is recorded to whoever did it, not that the software polices access.
CREATE TABLE app_user (
    user_id      TEXT PRIMARY KEY NOT NULL,
    login        TEXT UNIQUE NOT NULL,
    display_name TEXT
);

CREATE TABLE task (
    task_id     TEXT PRIMARY KEY NOT NULL,
    task_type   TEXT NOT NULL
        CHECK (task_type IN ('transcribe','review_flag','adjudicate_kanji',
                             'adjudicate_linkage','resolve_disappearance',
                             'validate_event','curate_deployment')),
    subject_id  TEXT,
    assigned_to TEXT REFERENCES app_user(user_id),
    status      TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open','in_progress','done','wontfix')),
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- The log of the work done: who recorded what, when, on which page.
--
-- This replaces the Postgres audit triggers, which kept full before/after row
-- images of everything. That was built for a compliance-grade guarantee nobody
-- asked for; what is actually wanted is a readable record of transcription
-- work, which exports to a spreadsheet and can be read by a person. The
-- provenance of a value still lives on the row itself: observation carries
-- author_user_id, created_at and status.
CREATE TABLE work_log (
    log_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    at         TEXT NOT NULL DEFAULT (datetime('now')),
    user_id    TEXT REFERENCES app_user(user_id),
    action     TEXT NOT NULL,                   -- 'record_officer' / 'register_cells' / ...
    volume_pid TEXT,
    frame_no   INTEGER,
    row_index  INTEGER,
    detail     TEXT                             -- JSON, optional
);

-- --------------------------------------------------------------------------
-- Indexes
-- --------------------------------------------------------------------------

CREATE INDEX observation_person_idx    ON observation (person_id);
CREATE INDEX observation_asof_idx      ON observation (as_of_date);
CREATE INDEX observation_unlinked_idx  ON observation (obs_id) WHERE person_id IS NULL;
CREATE INDEX kanpo_event_person_idx    ON kanpo_event (person_id);
CREATE INDEX kanpo_event_date_idx      ON kanpo_event (event_date);
CREATE INDEX kanpo_event_pending_idx   ON kanpo_event (event_id) WHERE validation_status = 'proposed';
CREATE INDEX roster_cell_page_idx      ON roster_cell (page_id);
CREATE INDEX roster_cell_flagged_idx   ON roster_cell (cell_id) WHERE audit_status <> 'ok';
CREATE INDEX unit_deployment_unit_idx  ON unit_deployment (unit_id, interval_start);
CREATE INDEX work_log_at_idx           ON work_log (at);
CREATE INDEX work_log_user_idx         ON work_log (user_id);
