"""Load the controlled vocabularies from data/vocab/*.csv into Postgres.

`db/schema.sql` creates rank_vocab, branch_vocab and kanji_variant but never
populates them, and nothing else did either — so on a fresh stack all three are
empty. That is not cosmetic: observation.rank_code and observation.branch_code are
foreign keys into those tables, so with them empty **no observation row can be
inserted at all**. This script closes that gap.

Emits SQL on stdout rather than talking to the database directly, so it needs no
driver and works against any psql — container, local install, or CI.

    python scripts/load_vocab.py                      # inspect the SQL
    python scripts/load_vocab.py | docker exec -i jpocr-db \
        psql -U jpocr -d jpocr -v ON_ERROR_STOP=1 -f -

Idempotent: every row is an upsert keyed on the primary key, so re-running after a
vocabulary edit updates in place. It does not delete rows that have been removed
from the CSVs — vocabularies are referenced by foreign keys, and silently dropping
a code that observations point at would fail loudly at best and orphan data at
worst. Removals are deliberate migrations, not a side effect of a reload.

`variants` is `;`-separated in the CSVs (the convention scripts/lint_vocab.py
enforces) and text[] in the schema.
"""
import csv
import sys
from pathlib import Path

VOCAB = Path(__file__).resolve().parent.parent / "data" / "vocab"


def q(value: str | None) -> str:
    """Quote a scalar as a SQL literal, or NULL for blank."""
    if value is None or value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def q_array(value: str | None) -> str:
    """Quote a ';'-separated variant list as a Postgres text[]."""
    items = [v.strip() for v in (value or "").split(";") if v.strip()]
    if not items:
        return "'{}'"
    return "ARRAY[" + ",".join(q(i) for i in items) + "]::text[]"


def rows(name: str):
    with open(VOCAB / name, newline="", encoding="utf-8") as f:
        yield from csv.DictReader(f)


def upsert(table: str, key: str, cols: list[str], values: list[str]) -> str:
    updates = ", ".join(f"{c} = EXCLUDED.{c}" for c in cols if c != key)
    return (
        f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({', '.join(values)})\n"
        f"  ON CONFLICT ({key}) DO UPDATE SET {updates};"
    )


def main() -> None:
    # The payload is Japanese, so stdout must not inherit the console codepage.
    # On a Japanese Windows console that is cp932, which cannot encode 步 (U+6B65)
    # in branch.csv — the script would die mid-emit, and anything piped to psql
    # has to be UTF-8 on the wire regardless.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", newline="\n")

    out = sys.stdout
    out.write("-- Generated by scripts/load_vocab.py. Do not edit by hand.\n")
    out.write("SET client_encoding = 'UTF8';\n")
    out.write("BEGIN;\n\n")

    out.write("-- rank_vocab\n")
    for r in rows("rank.csv"):
        out.write(upsert(
            "rank_vocab", "rank_code",
            ["rank_code", "label_ja", "label_en", "seniority_order",
             "variants", "valid_from", "valid_to"],
            [q(r["rank_code"]), q(r["label_ja"]), q(r["label_en"]),
             r["seniority_order"], q_array(r["variants"]),
             q(r["valid_from"]), q(r["valid_to"])],
        ) + "\n")

    out.write("\n-- branch_vocab\n")
    for b in rows("branch.csv"):
        out.write(upsert(
            "branch_vocab", "branch_code",
            ["branch_code", "label_ja", "label_en", "category",
             "variants", "valid_from", "valid_to"],
            [q(b["branch_code"]), q(b["label_ja"]), q(b["label_en"]),
             q(b.get("category")), q_array(b["variants"]),
             q(b["valid_from"]), q(b["valid_to"])],
        ) + "\n")

    out.write("\n-- kanji_variant\n")
    for k in rows("kanji_variant.csv"):
        out.write(upsert(
            "kanji_variant", "variant_char",
            ["variant_char", "canonical_char", "note"],
            [q(k["variant_char"]), q(k["canonical_char"]), q(k.get("note"))],
        ) + "\n")

    out.write("\nCOMMIT;\n")


if __name__ == "__main__":
    main()
